version: '2'                                                                                                                                                                                                

services:

  4store:                                                                                                                                                                                                                                  
    image: bde2020/4store:1.1.5                                                                                                                                                                                         
